# Generated by Django 5.0.3 on 2024-03-13 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Usuario',
        ),
    ]
